apiVersion: v1
kind: Pod
metadata:
  name: simplilearn-phpinfo-pod
spec:
  containers:
    - name: rabellaatbsc/simplilearn-phpinfo-dca-2021-05:latest
      image: rabellaatbsc/simplilearn-phpinfo-dca-2021-05:latest
      command: 
        - "php" 
      args: 
        - "-f"
        - "index.php"
        - "-S"
        - "0.0.0.0:8080"
 
